name: Create Tag and Release

on:
  push:
    branches:
      - beta

jobs:
  createTagAndRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Tag and Release
        run: |
          # Retrieve the current commit SHA
          COMMIT_SHA=$(git rev-parse HEAD)

          # Generate a unique tag name using the commit SHA
          TAG_NAME="v${COMMIT_SHA::8}"

          # Create a lightweight tag
          git tag $TAG_NAME $COMMIT_SHA

          # Push the tag to GitHub
          git push origin $TAG_NAME

          # Create a release associated with the tag
          API_URL="https://api.github.com/repos/${{ github.repository }}/releases"
          RELEASE_BODY="Release description"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"tag_name\":\"$TAG_NAME\",\"body\":\"$RELEASE_BODY\"}" $API_URL
